//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclaracionJurada
    {
        public int Id { get; set; }
        public bool Corresponde { get; set; }
        public int RequisitoId { get; set; }
        public int SolicitudLicenciaId { get; set; }
    
        public virtual Requisito Requisito { get; set; }
        public virtual SolicitudLicencia SolicitudLicencia { get; set; }
    }
}
