//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioUnicoTramite
    {
        public int Id { get; set; }
        public string Ruc { get; set; }
        public string Dni { get; set; }
        public string CarnetExtranjeria { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Telefax { get; set; }
    
        public virtual SolicitudLicencia SolicitudLicencia { get; set; }
        public virtual SolicitudAnuncio SolicitudAnuncio { get; set; }
    }
}
