//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giro
    {
        public Giro()
        {
            this.Requisitos = new HashSet<Requisito>();
            this.Licencias = new HashSet<Licencia>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string FechaRegistro { get; set; }
    
        public virtual ICollection<Requisito> Requisitos { get; set; }
        public virtual ICollection<Licencia> Licencias { get; set; }
    }
}
