//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GLicenciasBDContainer : DbContext
    {
        public GLicenciasBDContainer()
            : base("name=GLicenciasBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolUsuario> RolUsuario { get; set; }
        public virtual DbSet<CronogramaFiscalizacion> CronogramaFiscalizacion { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Licencia> Licencia { get; set; }
        public virtual DbSet<Fiscalizador> Fiscalizador { get; set; }
    }
}
