//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public Requisito()
        {
            this.FiscalizacionRequisitos = new HashSet<FiscalizacionRequisito>();
        }
    
        public int Id { get; set; }
        public string Valor { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int GiroId { get; set; }
        public int CriterioId { get; set; }
    
        public virtual Giro Giro { get; set; }
        public virtual Criterio Criterio { get; set; }
        public virtual ICollection<FiscalizacionRequisito> FiscalizacionRequisitos { get; set; }
    }
}
