//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAnuncio
    {
        public int Id { get; set; }
        public string Grafico { get; set; }
        public string Leyenda { get; set; }
        public string Color { get; set; }
        public decimal Largo { get; set; }
        public decimal Alto { get; set; }
        public decimal Ancho { get; set; }
    
        public virtual FormularioUnicoTramite FormularioUnicoTramite { get; set; }
    }
}
