//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licencias.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.RolUsuarios = new HashSet<RolUsuario>();
            this.CronogramaFiscalizacions = new HashSet<CronogramaFiscalizacion>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<RolUsuario> RolUsuarios { get; set; }
        public virtual ICollection<CronogramaFiscalizacion> CronogramaFiscalizacions { get; set; }
    }
}
